### ISSUE TITLE
تغییر نکردن عدد سال هنگام رفتن به سال جدید

### ISSUE THREAD

**Issue by yaser-p** [Azare77/jalali_table_calendar#10]
سلام.خسته نباشید
وقتی از اسفند 1402 میرم فروردین 1403 عدد سال تغییر نمیکنه و 1402 میمونه.البته ماه بعدی که اردیبهشت هست درست میشه.

**Comment by Azare77** [comment]
مشکل برطرف شد با تشکر از گزارش شما
