### ISSUE TITLE
Multi-select support

### ISSUE THREAD

**Issue by AliRezaBeitari** [Azare77/jalali_table_calendar#3]
It would be really useful if you provide some way to select multiple days on the calendar.

**Comment by Azare77** [comment]
کامبک زدم رو توسعه پکیج و حتما در نظرم میگیرم اینو
 فقط چون این پکیج از روی یکی دیگه ساخته شده چالشش زیاده

**Comment by Azare77** [comment]
ویزگی مورد نظر اضافه شد
