### ISSUE TITLE
localization and change format to persian

### ISSUE THREAD

**Issue by AbbasHoseini** [Azare77/jalali_table_calendar#4]
Hi. Thanks for this  useful package.
I searched about locale to convert English numbers to persian numbers, but got an error. and I couldnt find any good document for that. 
 سلام و سپاس بابت پکیج مفیدتان.
درباره ی تبدیل شماره های انگلیسی به فارسی سرچ کردم و اموری انجام دادم اما ارور دریافت کردم. همچنین منبع خوبی برای پیاده سازی آن پیدا نکردم. ممنون میشم راهنمایی کنید.

**Comment by Azare77** [comment]
hi adding localization support is in the plan i will add it as soon as possible
