### ISSUE TITLE
get event text

### ISSUE THREAD

**Issue by mohsen0fc** [Azare77/jalali_table_calendar#5]
Hi, thanks for the great package
Please guide me how to get the text of the recorded events
سلام ممنون بابت پکیج عالی
لطفا راهنمایی کنید متن ایونت های ثبت شده رو چطور میتونم دریافت کنم

**Comment by Azare77** [comment]
ایونت ها به صورت Map به پکیج داده میشه و پس از اننتخاب یک روز تاریخ آن به کاربر برگشت داده میشه تا کابر بتونه بر اساس اون تاریخ ایونت های مرتبط رو از map دریافت کنه
