### ISSUE TITLE
events for month change

### ISSUE THREAD

**Issue by hrmoh** [Azare77/jalali_table_calendar#6]
Hi,
I need to know when user changes current month or year and know the first day and the last one for current page to query events related to selected range from my service, can you add some additional delegates such as onDaySelected to send notifications on these subjects?

سلام

من نیاز دارم وقتی کاربر ماه جاری را تغییر می‌دهد، اولا از این رویداد مطلع بشوم، ثانیا اطلاعات ماه جاری را بدانم تا بر اساس آن اطلاعات ماه انتخاب شدهٔ کاربر را شامل تعدادی رویداد از سرویسم دریافت کنم.
در حال حاضر تنها رویداد onDaySelected در دسترس است که کافی نیست و عموما وقتی ماه تغییر می‌کند روز جاری انتخاب شده خارج از بازهٔ ماه جاری است.
اضافه شدن این رویدادها به حل این مشکل کمک می‌کند.
متشکر

**Comment by Azare77** [comment]
با تاخیر زیاد انجام شد
