### ISSUE TITLE
events دریافت متن 

### ISSUE THREAD

**Issue by yaser-p** [Azare77/jalali_table_calendar#9]
با سلام و تشکر
لطفا بفرمایید اگر من events بصورت زیر داشته باشم:
  today:   const ['unknown','2'],
چطور میتونم دومین آیتم که همون عدد 2 هست رو دریافت کنم؟
قاعداتا باید بشه events![1]  . ولی خطا میده !

**Comment by Azare77** [comment]
من خیلی وقته روی این پکیج کار نکردم دقیق تو نطرم نیست اما example خودشو که اجرا می‌کنی چه نتیجه ای میگیری

**Comment by yaser-p** [comment]
تو مثالش تعداد آیتم رو فقط گرفته . و مقدا آیتم ها رو مثال نداره.

**Comment by Azare77** [comment]
اوکی یه کامبک میزنم روش تا کلا بهبودش بدم
